version: '3.8'

# ML Optimization Framework - Simplified Single Service
# Automatically runs demos and starts Optuna dashboard

networks:
  ml-optimization-network:
    driver: bridge

volumes:
  studies-data:
    driver: local
  logs-data:
    driver: local
  results-data:
    driver: local

services:
  # ML Optimization Service - Auto Demo + Optuna Dashboard
  ml-optimization:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-optimization-framework
    ports:
      - "${OPTUNA_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - studies-data:/app/studies
      - logs-data:/app/logs
      - results-data:/app/results
    environment:
      - PYTHONUNBUFFERED=1
      - OPTUNA_DASHBOARD_HOST=0.0.0.0
      - OPTUNA_DASHBOARD_PORT=8080
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
    restart: unless-stopped
    command: ["sh", "-c", "python create_unified_demo.py && optuna-dashboard sqlite:///studies/unified_demo.db --host 0.0.0.0 --port 8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - ml-optimization-network
