version: '3.8'

services:
  # Streamlit Dashboard Service (Primary Interface)
  streamlit:
    build:
      context: .
      target: base
    container_name: ml-streamlit-dashboard
    command: ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501", "--browser.gatherUsageStats=false"]
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    volumes:
      - .:/home/mlopt/app
      - ./studies:/home/mlopt/app/studies
      - ./results:/home/mlopt/app/results
      - ./logs:/home/mlopt/app/logs
    environment:
      - PYTHONPATH=/home/mlopt/app
      - DATABASE_URL=${DATABASE_URL:-sqlite:///studies/optuna_studies.db}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - ml-network
    restart: unless-stopped

  # Optuna Dashboard Service
  optuna-dashboard:
    build:
      context: .
      target: base
    container_name: ml-optuna-dashboard
    command: ["python", "scripts/start_dashboard.py"]
    ports:
      - "${DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ./studies:/home/mlopt/app/studies
    environment:
      - PYTHONPATH=/home/mlopt/app
      - DATABASE_URL=${DATABASE_URL:-sqlite:///studies/optuna_studies.db}
    networks:
      - ml-network
    restart: unless-stopped

networks:
  ml-network:
    driver: bridge
