version: '3.8'

networks:
  ml-optimization-network:
    driver: bridge

volumes:
  studies-data:
    driver: local
  logs-data:
    driver: local

services:
  # Streamlit Application Service - Main Web Interface
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-optimization-streamlit
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    volumes:
      - studies-data:/app/studies
      - logs-data:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_HOST=0.0.0.0
      - STREAMLIT_PORT=8501
      - OPTUNA_DASHBOARD_URL=http://optuna-dashboard:8080
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
    restart: unless-stopped
    command: ["python", "docker-start.py", "streamlit"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    networks:
      - ml-optimization-network
    depends_on:
      - optuna-dashboard

  # Optuna Dashboard Service - Optimization Visualization
  optuna-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-optimization-optuna-dashboard
    ports:
      - "${OPTUNA_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - studies-data:/app/studies
      - logs-data:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - OPTUNA_DASHBOARD_HOST=0.0.0.0
      - OPTUNA_DASHBOARD_PORT=8080
      - SERVICE_TYPE=dashboard
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
    restart: unless-stopped
    command: ["python", "docker-start.py", "dashboard"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - ml-optimization-network
